### ISSUE TITLE
After typing a search word, pressing enter hits the first search result

### ISSUE THREAD

**Issue by kcmannem** [zaru/menuffy#2]
Currently after you search for something, hitting enter doesn't do anything. You need to use the arrow keys to pick the option you want.
Allow us to press enter after searching and automatically choose the first result.

**Comment by zaru** [comment]
@kcmannem Thank you for your feedback. I've created a PR and will release it soon.

**Comment by kcmannem** [comment]
@zaru thanks for the quick fix!
